name = "CourseMatch"
uuid = "2023c74b-2655-53ae-8182-f77462f41c2f"
authors = ["florian oswald <florian.oswald@gmail.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
